image: Visual Studio 2015
version: "1.0.0-development-{build}"
configuration:
  - Release

init:
  - git config --global core.autocrlf input
  
before_build:
  - ps: .\Set-PackageLabel.ps1
  - dotnet restore -v minimal
  
build:
  project: EFAuditing.sln
  parallel: false
  verbosity: minimal

after_build:
  - dotnet test .\test\EFAuditing.TestHarness -trait "Category=A"
  - dotnet pack -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts .\src\EFAuditing\project.json

# Couldn't get the default build runner to execute tests in Auto mode
test: off

artifacts:
  - path: artifacts\*.nupkg

deploy:
  - provider: NuGet
    server: https://novaworks.myget.org/F/parliament-ci/api/v2/package
    api_key:
      secure: 8CsS42Ic+vTW/DhHUAJ5KreTtOCnHDvzPwLJebjUQelchOvjhskEZFJ4EIR9tV3F
    skip_symbols: false
    symbol_server: https://novaworks.myget.org/F/parliament-ci/symbols/api/v2/package
    artifact: /.*\.nupkg/
    on:
      configuration: Release
      appveyor_repo_tag: false # do not deploy to this feed on tag push
