image: Visual Studio 2015
version: "1.0.0-development-{build}"
configuration:
  - Release

init:
  - git config --global core.autocrlf input

test: off

before_build:
  - dotnet restore -v minimal

build:
  project: EFAuditing.sln
  parallel: true
  verbosity: minimal

after_build:
  - dotnet pack -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts .\src\EFAuditing\project.json


artifacts:
  - path: artifacts\*.nupkg

deploy:
#  - provider: NuGet
#    server: https://novaworks.myget.org/F/parliament-ci/api/v2/package
#    api_key:
#      secure: 8CsS42Ic+vTW/DhHUAJ5KreTtOCnHDvzPwLJebjUQelchOvjhskEZFJ4EIR9tV3F
#    skip_symbols: false
#    symbol_server: https://novaworks.myget.org/F/parliament-ci/symbols/api/v2/package
#    artifact: /.*\.nupkg/
#    on:
#      configuration: Release
#      appveyor_repo_tag: false # do not deploy to this feed on tag push

environment:
#  nuget_user: oconicsci
#  nuget_password:
#     secure: Xo8KvyMsnePdmUCFmvQjMiNdAyc6qThdZukA+h+herA=
